openapi: 3.0.0
info:
  title: Cart API
  description: >
    Cart API for microservices architecture e-commerce web using polyglot persistance
    data storage
  version: 0.0.1
# servers:
#   - url: http://api.example.com/v1
#     description: Optional server description, e.g. Main (production) server
#   - url: http://staging-api.example.com
#     description: Optional server description, e.g. Internal staging server for testing
paths:
  /cart/{id}:
    get:
      summary: Get users cart
      description: Returns a list of products and their quantities in a users cart
      parameters:
        - $ref: "#/components/parameters/id"
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
